#!/usr/bin/env python3
"""
Test Project
A test project

Generated by MIA Project AGI System
"""

import logging
import sys
from pathlib import Path

# Add src to path
sys.path.insert(0, str(Path(__file__).parent / "src"))

# Setup logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)

logger = logging.getLogger(__name__)


def main():
    """Main application entry point"""
    logger.info("Starting Test Project...")
    
    try:
        # Application logic here
        logger.info("Test Project started successfully")
        
        # Keep running for web apps
        if "ProjectType.CLI_TOOL" in ["ProjectType.WEB_APP", "ProjectType.API_SERVICE"]:
            import uvicorn
            uvicorn.run("app:app", host="0.0.0.0", port=8000, reload=True)
        else:
            logger.info("Test Project completed")
            
    except KeyboardInterrupt:
        logger.info("Shutting down...")
    except Exception as e:
        logger.error(f"Error: {e}")
        sys.exit(1)


if __name__ == "__main__":
    main()
